all:
  hosts:
    netology-develop-platform-web-0:
        ansible_host: 51.250.2.74
        ansible_user: ubuntu
    netology-develop-platform-web-1:
        ansible_host: 51.250.69.236
        ansible_user: ubuntu
    bastion:
        ansible_host: 51.250.14.18
        ansible_user: ubuntu
  