all:
  hosts:
    netology-develop-platform-web-0:
        ansible_host: 
        ansible_user: ubuntu
    netology-develop-platform-web-1:
        ansible_host: 
        ansible_user: ubuntu
    bastion:
        ansible_host: 89.169.134.136
        ansible_user: ubuntu
  