---
- name: test
  gather_facts: false
  hosts: webservers
  vars:
    ansible_ssh_user: ubuntu
  become: yes

  pre_tasks:
    - name: Validating the ssh port is open and
      wait_for:
        host: "{{ansible_host}}"
        port: 22
        delay: 0
        timeout: 600
        state: started
        msg: "ssh server is not running"

    - name: Check known_hosts for {{ inventory_hostname }}
      local_action: shell ssh-keygen -F {{ inventory_hostname }}
      register: has_entry_in_known_hosts_file
      changed_when: false
      ignore_errors: true
    - name: Ignore host key for {{ inventory_hostname }} on first run
      when: has_entry_in_known_hosts_file.rc == 1
      set_fact:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Install Nginx Web Server on Debian Family
      apt:
        name:
          - nginx
          - jq
        state: latest
        update_cache: yes

    # cat /tmp/own.pass  | jq
    - name: save own secret
      copy:
        dest: /tmp/own.pass
        content: "{{ secrets[inventory_hostname]  }}"
      when: secrets[inventory_hostname] is defined

    # cat /tmp/all.pass  | jq
    - name: save all secrets
      copy:
        dest: /tmp/all.pass
        content: "{{ secrets }}"
      when: secrets is defined
